site_name: My Docs
docs_dir: "docs"
nav:
  - FULL:
      - Gclass1: Gclass1.md
      - Dclass1: Dclass1.md
      - Gclass2: Gclass2.md
      - Dclass2: Dclass2.md
      - Gclass3: Gclass3.md
      - Dclass3: Dclass3.md
      - Gclass4: Gclass4.md
      - Dclass4: Dclass4.md
      - Gclass5: Gclass5.md
      - Dclass5: Dclass5.md
      - Gclass6: Gclass6.md
      - Dclass6: Dclass6.md
      - Gclass7: Gclass7.md
      - Dclass7: Dclass7.md
      - Gclass8: Gclass8.md
      - Dclass8: Dclass8.md
  - MasterClass:
      - Masterclass0: Masterclass0.md
      - Masterclass1: Masterclass1.md
      - Masterclass2: Masterclass2.md
      - Masterclass2A: Masterclass2A.md
      - Masterclass2B: Masterclass2B.md
      - Masterclass3: Masterclass3.md
      - Masterclass4: Masterclass4.md
      - Masterclass5: Masterclass5.md
      - Masterclass6: Masterclass6.md
      - Masterclass7: Masterclass7.md
      - Masterclass8: Masterclass8.md
      - Masterclass9: Masterclass9.md
      - Masterclass10: Masterclass10.md
      - Masterclass11: Masterclass11.md
      - Masterclass12: Masterclass12.md
      - Masterclass13: Masterclass13.md
      - Masterclass14: Masterclass14.md
      - Masterclass15: Masterclass15.md

  - Fix: FixingApp.md
  - Grokking:
      - SECTION 0: section 0.md
      - SECTION 1: section 1.md
      - SECTION 2: section 2.md
      - SECTION 2R: section 2 refactor.md
      - SECTION 3: section 3.md
      - SECTION 4: section 4.md
      - SECTION 5: section 5.md
      - SECTION 6: section 6.md
      - SECTION 7: section 7.md
      - SECTION 8: section 8.md
  - Chatting:
      - Stage0: gptStage0.md
      - Stage2.1: gptStage2.1.md
      - Stage2: gptStage2.md
      - Stage3.1: gptStage3.1.md
      - Stage4.1: gptStage4.1.md
      - Stage4.2: gptStage4.2.md
      - Stage4.3: gptStage4.3.md
      - Stage4.5: gptStage4.5.md
      - Stage5.1: gptStage5.1.md
      - Stage5.2: gptStage5.2.md
      - Stage5.3: gptStage5.3.md
      - Stage5.4: gptStage5.4.md
      - Stage6.1: gptStage6.1.md
      - Stage6.2: gptStage6.2.md
      - Stage6.3: gptStage6.3.md
      - Stage6.4: gptStage6.4.md
      - Stage6.5: gptStage6.5.md
      - Stage6.6: gptStage6.6.md
      - Stage7.0: gptStage7.0.md
      - Stage7.1: gptStage7.1.md
      - Stage7.2: gptStage7.2.md

  - CLAUD: claud.md
  - ADDitional: addintionalClaud.md
  - AdditionalGem: again.md
  - GROK: grok2.md
  - GEMINI: index.md
  - GPT: tricks.md
  - FINAL: CLAUD2.md
  - GPT: gpt2.0.md
  - ClaudCSS: CSS_claud.md
  - GEMCSS: GemsCSS.md
  - Cluadpy: claud.py.md
  - GEMJS: gemsJS.md
  - GEMFinal: final_expansions.md
  - GrokF: grokf.md
  - newEx: newExp.md
  - OneFile: oneFile.md
  - CLose: anohteron.md
  - List: structure.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - navigation.instant
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - css/overrides.css
